### ISSUE TITLE
Expressing love

### ISSUE THREAD

**Issue by HelloElwin** [HKUAstar/Standard#1]
Hi! Just passing by this repo and find it **_so attractive_**!!! The author (**_Shaoyu_**!!) is doing such a good job! What a **_perfect_** structure and README.md! _**Love**_ it!!!! Any one else wanna express love? React to my issue!

**Comment by Carbonadooo** [comment]
Thank you so much! This is my very first time to make such a repo. Please let me know if there is anything I can improve! Thanks again to Elwin!
